apiVersion: batch/v1
kind: Job
metadata:
  name: imdb-trainer-{{INCREMENTAL_NUMBER}}
spec:
  template:
    metadata:
      labels:
        job-type: trainer
    spec:
      restartPolicy: Never
      containers:
      - image: kkp6249/imdb-kubernetes:trainer-1.0.0 # 2019. 03. 16 Added relu share
        args: ["--data", "/imdb/data/{{INCREMENTAL_NUMBER}}.npz", 
               "--epoch", "{{EPOCH}}", "--batch", "{{BATCH}}", 
               "--savefile", "/imdb/model/{{INCREMENTAL_NUMBER}}-model.h5"]
        imagePullPolicy: Always
        name: imdb-trainer-job
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: "/imdb"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
               matchExpressions:
                  - key: "job-type"
                    operator: In
                    values:
                      - trainer
              topologyKey: "kubernetes.io/hostname"

      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
