apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        name: busybox
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/imdb"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
