apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: imdb-server
  template:
    metadata:
      labels:
        name: imdb-server
    spec:
      containers:
      - image: kkp6249/imdb-kubernetes:1.0.0
        imagePullPolicy: Always
        name: imdb-server
        args: ["--model", "/imdb/aggregated-model.h5"]
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: "/imdb"
        ports:
        - containerPort: 5000
          name: flask
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: imdb-server-svc
spec:
  ports:
    - name: service
      port: 80
      targetPort: 5000
  selector:
    name: imdb-server
  type: LoadBalancer
